<?php require APP_ROOT_URL .'/views/inc/header.phtml';?>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-3">
            <?php echo $data['title'] ?>
        </h1>
        <p class="lead">
            <?php echo $data['description'] ?>
        </p>
        <p class="lead">
            <strong><?php echo APP_VERSION; ?></strong>
        </p>
    </div>
</div>

<?php require APP_ROOT_URL.'/views/inc/footer.phtml';?>