<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
<div class="container">
  <a class="navbar-brand" href="<?php echo BASE_URL ?>"><?php echo SITENAME; ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<?php echo BASE_URL ?>">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo BASE_URL ?>/pages/about">About</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">

      <?php if(isset($_SESSION['user_id'])) : ?>

      <li class="nav-item">
        <?php /*Warum $_SESSION['user_name']; ? Schau mal in den User-Controller in die createUserSession()! */?>
        <a class="nav-link" href="#">Schön, dass du da bist, <?php echo $_SESSION['user_name']; ?></a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="<?php echo BASE_URL ?>/users/logout">Ausloggen </a>
      </li>

      <?php else : ?> 
      <li class="nav-item active">
        <a class="nav-link" href="<?php echo BASE_URL ?>/users/register">Register </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo BASE_URL ?>/users/login">Login</a>
      </li>
  	  <?php endif; ?>
    </ul>


  </div>
</div>
</nav>