<?php require APP_ROOT_URL .'/views/inc/header.phtml';?>
<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card card-body bg-light mt-5">
            <?php flash('register_success'); ?>
            <div class="h2">Anmelden</div>
            <p>Gib deine Zugangsdaten ein, um dich einzuloggen:</p>

            <form action="<?php echo BASE_URL; ?>/users/login" method="POST">
            
                <div class="form-group">
                    <label for="email">E-Mail: <sup>*</sup></label>
                    <input type="email" name="email" 
                    class="form-control form-control-lg <?php echo (!empty($data['email_error'])) ? 'is-invalid' : ''; ?>" 
                    value="<?php echo $data['email']; ?>">
                    <span class="invalid-feedback"><?php echo $data['email_error']; ?></span>
                </div>
                <div class="form-group">
                    <label for="password">Password: <sup>*</sup></label>
                    <input type="password" name="password" 
                    class="form-control form-control-lg <?php echo (!empty($data['password_error'])) ? 'is-invalid' : ''; ?>" 
                    value="<?php echo $data['password']; ?>">
                    <span class="invalid-feedback"><?php echo $data['password_error']; ?></span>
                </div>
               
                <div class="row">
                    <div class="col">
                        <input type="submit" value="Einloggen" class="btn btn-success btn-block">
                    </div>
                    <div class="col">
                        <a href="<?php echo BASE_URL; ?>/users/register" class="btn btn-light btn-block">Registrieren</a>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>
<?php require APP_ROOT_URL.'/views/inc/footer.phtml';?>